# Generated by Django 3.1.4 on 2020-12-14 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoins',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderCoins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SellCoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('payment_mode', models.CharField(default='Paytm', max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('trasaction_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SellCoins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
