# Generated by Django 3.1.4 on 2020-12-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
