# Generated by Django 3.1.4 on 2021-01-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_ordercoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercoinrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
