# Generated by Django 3.1.4 on 2020-12-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20201221_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('app_id', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=1000)),
                ('use', models.BooleanField(default=False)),
            ],
        ),
    ]
