# Generated by Django 3.1.4 on 2020-12-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_reffralbonous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoins',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reffralbonous',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sellcoins',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
