# Generated by Django 3.1.4 on 2020-12-29 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_reffraltable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reffraltable',
            name='refer',
        ),
        migrations.AddField(
            model_name='reffraltable',
            name='refer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='refer', to=settings.AUTH_USER_MODEL),
        ),
    ]
