# Generated by Django 3.1.4 on 2021-01-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_help_history_topwinners'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_type',
            field=models.CharField(default='PLUS', max_length=100),
        ),
    ]
