# Generated by Django 3.1.4 on 2021-01-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputedgame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
