# Generated by Django 3.1.4 on 2020-12-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='amount',
            new_name='coins',
        ),
    ]
