# Generated by Django 3.1.4 on 2020-12-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201214_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='requested_players',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
