# Generated by Django 3.1.4 on 2021-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_disputedgame_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='room_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
