# Generated by Django 3.1.4 on 2020-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_is_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_one',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_two',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
