# Generated by Django 3.1.4 on 2020-12-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20201215_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
