# Generated by Django 3.1.4 on 2020-12-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20201216_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='reason_of_cancel',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='result',
            field=models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST'), ('CANCEL', 'CANCEL')], max_length=25),
        ),
    ]
