# Generated by Django 3.1.4 on 2020-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201216_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='reason_of_cancel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
