# Generated by Django 3.1.4 on 2020-12-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_gameresult_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='requested_players',
            field=models.CharField(default=',', max_length=500),
        ),
    ]
