# Generated by Django 3.1.4 on 2020-12-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20201218_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='result',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('WON', 'WON'), ('LOST', 'LOST'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=25),
        ),
    ]
