# Generated by Django 3.1.4 on 2020-12-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20201218_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputedgame',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
