# Generated by Django 3.1.4 on 2020-12-22 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0015_disputedgame_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='result_by_player_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_by_player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='result_by_player_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_by_player_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
