# Generated by Django 3.1.4 on 2020-12-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20201222_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('RUNNING', 'RUNNING'), ('WAITING', 'WAITING'), ('OVER', 'OVER')], default='CREATED', max_length=100),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='winning_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
