# Generated by Django 3.1.4 on 2020-12-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
