# Generated by Django 3.1.4 on 2020-12-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_image_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='winning_amount',
            field=models.IntegerField(default=0),
        ),
    ]
